version: "3.7"

services:
  mc_large:
    image: itzg/minecraft-server
    ports:
    - 25565:25565
    environment:
      MAX_MEMORY: 6G
      MAX_BUILD_HEIGHT: 256
      VIEW_DISTANCE: 15
      LEVEL_TYPE: LARGEBIOMES
      MAX_PLAYERS: 10
      CONSOLE: "false"
      # REQUIRED for all types
      EULA: "TRUE"
      # Set server type (vs the default of vanilla)
      TYPE: SPIGOT
    restart: always
    volumes:
    - ./large_data:/data

